Repository coding-union-kr/youare-iam-be, pull requests merged in 2023-12, with the labels that each got.

#4 feat: Swagger 세팅 #2
  build.gradle
  common/src/main/java/com/letter/config/SwaggerConfig.java
  common/src/main/resources/application.yml
Labels: feature

#6 feat:QueryDSL 세팅 #5
  storage/build.gradle
Labels: feature

#16 feat: Entity 생성
  storage/build.gradle
  storage/src/main/java/com/letter/member/entity/Couple.java
  storage/src/main/java/com/letter/member/entity/InviteOpponent.java
  storage/src/main/java/com/letter/member/entity/Member.java
  storage/src/main/java/com/letter/question/entity/Answer.java
  storage/src/main/java/com/letter/question/entity/Question.java
  storage/src/main/java/com/letter/question/entity/RegisterQuestion.java
  storage/src/main/java/com/letter/question/entity/SelectQuestion.java
Labels: feature, fix

#17 feat, fix: Entity 변경 사항, Config 파일 추가, Build 실패 해결
  common/build.gradle
  domain/build.gradle
  storage/build.gradle
  storage/src/main/java/com/letter/config/QueryDslConfig.java
  storage/src/main/java/com/letter/member/entity/Couple.java
  storage/src/main/java/com/letter/member/entity/InviteOpponent.java
  storage/src/main/java/com/letter/member/entity/Member.java
  storage/src/main/java/com/letter/question/entity/Answer.java
  storage/src/main/java/com/letter/question/entity/Question.java
  storage/src/main/java/com/letter/question/entity/RegisterQuestion.java
  storage/src/main/java/com/letter/question/entity/SelectQuestion.java
Labels: feature, fix

#18 feat: 질문 조회 #8
  common/src/main/java/com/letter/question/QuestionController.java
  domain/src/main/java/com/letter/question/service/QuestionService.java
  storage/src/main/java/com/letter/question/dto/QuestionResponse.java
  storage/src/main/java/com/letter/question/repository/QuestionCustomRepository.java
  storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
  storage/src/main/java/com/letter/question/repository/QuestionRepository.java
Labels: feature

#19 feat: JPA Auditing 허용
  build.gradle
  common/src/main/java/com/letter/CommonApplication.java
  domain/build.gradle
  storage/build.gradle
Labels: feature

#21 refactor: DB 변경으로 인한 코드 변경
  storage/src/main/java/com/letter/member/entity/Couple.java
  storage/src/main/java/com/letter/member/entity/Member.java
  storage/src/main/java/com/letter/question/entity/Question.java
Labels: refactor

#22 feat: 소셜 로그인 관련 api #1
  common/src/main/java/com/letter/member/OAuthController.java
  domain/src/main/java/com/letter/member/MemberService.java
  domain/src/main/java/com/letter/member/OAuthService.java
  storage/src/main/java/com/letter/member/dto/OAuthResponse.java
  storage/src/main/java/com/letter/member/entity/Member.java
  storage/src/main/java/com/letter/member/repository/MemberRepository.java
Labels: feature

#23 feat: access token 발급 #3
  build.gradle
  common/src/main/java/com/letter/member/OAuthController.java
  domain/src/main/java/com/letter/jwt/JwtProperties.java
  domain/src/main/java/com/letter/member/OAuthService.java
  storage/src/main/java/com/letter/member/dto/OAuthResponse.java
Labels: feature

#29 refactor: 누락 코드 수정
  storage/src/main/java/com/letter/member/entity/Member.java
  storage/src/main/java/com/letter/question/dto/QuestionResponse.java
  storage/src/main/java/com/letter/question/entity/RegisterQuestion.java
  storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
Labels: refactor

#32 feat: InviteOpponent 엔티티에 칼럼 추가 #31
  storage/src/main/java/com/letter/member/entity/InviteOpponent.java
Labels: feature

#33 feat: 질문 선택 API 요구사항 #26
  common/src/main/java/com/letter/question/QuestionController.java
  domain/src/main/java/com/letter/question/service/QuestionService.java
  storage/src/main/java/com/letter/question/dto/QuestionResponse.java
Labels: feature

#35 Feat/auth: jwt 토큰 생성 로직 수정
  domain/src/main/java/com/letter/member/OAuthService.java
Labels: refactor

#36 feat: 답변 등록 #11
  common/src/main/java/com/letter/question/AnswerController.java
  domain/src/main/java/com/letter/question/service/AnswerService.java
  storage/src/main/java/com/letter/question/dto/AnswerRequest.java
  storage/src/main/java/com/letter/question/entity/Answer.java
  storage/src/main/java/com/letter/question/repository/AnswerRepository.java
Labels: feature

#41 Feat/auth: cors 에러 해결을 위한 config파일 추가
  common/src/main/java/com/letter/config/WebConfig.java
Labels: feature

#43 fix: cors 에러 해결 및 클라이언트에서 헤더에 접근허용 설정 추가 #42
  common/src/main/java/com/letter/config/WebConfig.java
  common/src/main/java/com/letter/member/OAuthController.java
Labels: fix

#45 Feat/auth: 초대된 링크로 랜딩되는 페이지 관련 api #28
  common/src/main/java/com/letter/member/MemberController.java
  domain/src/main/java/com/letter/member/MemberService.java
  storage/src/main/java/com/letter/member/dto/MemberRequest.java
  storage/src/main/java/com/letter/member/dto/MemberResponse.java
Labels: feature

#47 feat: 대화방 질문 리스트 조회 #10
  common/src/main/java/com/letter/question/QuestionController.java
  domain/src/main/java/com/letter/question/service/QuestionService.java
  storage/src/main/java/com/letter/question/dto/AnswerResponse.java
  storage/src/main/java/com/letter/question/dto/DetailAnswerDto.java
  storage/src/main/java/com/letter/question/dto/LetterDetailResponse.java
  storage/src/main/java/com/letter/question/dto/LetterPaginationDto.java
  storage/src/main/java/com/letter/question/repository/AnswerCustomRepository.java
  storage/src/main/java/com/letter/question/repository/AnswerCustomRepositoryImpl.java
  storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
Labels: feature

#49 feat: 커스텀 Exception 생성 #20
  storage/src/main/java/com/letter/exception/CustomException.java
  storage/src/main/java/com/letter/exception/ErrorCode.java
  storage/src/main/java/com/letter/exception/ExceptionResponse.java
  storage/src/main/java/com/letter/exception/handler/GlobalExceptionHandler.java
Labels: feature

#51 refactor: Question, Answer 예외 핸들링 코드 추가 #50
  domain/src/main/java/com/letter/question/service/AnswerService.java
  domain/src/main/java/com/letter/question/service/QuestionService.java
  storage/src/main/java/com/letter/exception/ErrorCode.java
Labels: refactor

#58 Feat/auth: jwt 관련 로직 jwtProvider 파일로 분리 및 로그인 확인 커스텀 어노테이션 생성
  common/src/main/java/com/letter/annotation/LoginCheck.java
  common/src/main/java/com/letter/config/WebConfig.java
  common/src/main/java/com/letter/interceptor/LoginCheckInterceptor.java
  common/src/main/java/com/letter/member/MemberController.java
  domain/src/main/java/com/letter/jwt/JwtProperties.java
  domain/src/main/java/com/letter/jwt/JwtProvider.java
  domain/src/main/java/com/letter/member/MemberService.java
  domain/src/main/java/com/letter/member/OAuthService.java
  storage/src/main/java/com/letter/exception/ErrorCode.java
Labels: feature, refactor

#59 feat, refactor
  common/src/main/java/com/letter/annotation/LoginCheck.java
  common/src/main/java/com/letter/config/WebConfig.java
  common/src/main/java/com/letter/interceptor/LoginCheckInterceptor.java
  common/src/main/java/com/letter/member/MemberController.java
  domain/src/main/java/com/letter/jwt/JwtProperties.java
  domain/src/main/java/com/letter/jwt/JwtProvider.java
  domain/src/main/java/com/letter/member/MemberService.java
  domain/src/main/java/com/letter/member/OAuthService.java
  domain/src/main/java/com/letter/question/service/QuestionService.java
  storage/src/main/java/com/letter/exception/ErrorCode.java
  storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
Labels: feature, refactor

#62 deploy: Github Action과 AWS EB를 이용한 배포 #7
  .ebextentions
  .github/workflows/deploy.yml
  Dockerrun.aws.json
  common/Dockerfile
  common/build.gradle
  common/src/main/java/com/letter/aws/EbHealthCheck.java
  common/src/main/resources/application-local.yml
  common/src/main/resources/application-prod.yml
  common/src/main/resources/application.yml
  domain/src/main/resources/application-domain.yml
  storage/src/main/resources/application-sotrage.yml
Labels: chore

#63 fix: deploy.yml 수정
  .github/workflows/deploy.yml
Labels: fix

#64 fix: deploy.yml 수정
  .github/workflows/deploy.yml
Labels: fix

#65 fix: Dockerfile 수정
  common/Dockerfile
Labels: fix

#66 fix: Dockerfile 수정
  .github/workflows/deploy.yml
  common/Dockerfile
Labels: fix

#67 fix: Dockerfile 수정
  common/Dockerfile
Labels: fix

#68 fix: deploy.yml 수정
  .github/workflows/deploy.yml
Labels: fix

#69 fix: deploy.yml 수정
  .github/workflows/deploy.yml
Labels: fix

#70 rename: 파일 이름 오타 수정
  .ebextensions
Labels: rename

#71 fix: deploy.yml
  .github/workflows/deploy.yml
Labels: fix

#72 fix: deploy.yml
  .github/workflows/deploy.yml
Labels: fix

#73 fix: deploy.yml
  .github/workflows/deploy.yml
Labels: fix

#61 fix:초대 링크로 랜딩되는 페이지 관련 api 수정 및 리팩토링 #60
  common/src/main/java/com/letter/annotation/LoginCheck.java
  common/src/main/java/com/letter/interceptor/LoginCheckInterceptor.java
  common/src/main/java/com/letter/member/MemberController.java
  domain/src/main/java/com/letter/member/MemberService.java
  storage/src/main/java/com/letter/exception/ErrorCode.java
  storage/src/main/java/com/letter/member/dto/MemberResponse.java
  storage/src/main/java/com/letter/member/entity/InviteOpponent.java
  storage/src/main/java/com/letter/member/repository/InviteOpponentCustomRepository.java
  storage/src/main/java/com/letter/member/repository/InviteOpponentCustomRepositoryImpl.java
Labels: fix, refactor

#74 fix: deploy.yml
  .github/workflows/deploy.yml
Labels: fix

#75 fix: deploy.yml
  .github/workflows/deploy.yml
Labels: fix

#76 fix: deploy.yml
  .github/workflows/deploy.yml
Labels: fix

#79 chore: Deploy 관련 파일 수정
  .github/workflows/deploy.yml
  common/Dockerfile
  common/src/main/resources/application-prod.yml
Labels: chore

#80 fix: deploy.yml 수정
  .github/workflows/deploy.yml
  Dockerrun.aws.json
Labels: fix

#78 fix: 내 답변이 false로 오는 문제 #77
  common/src/main/resources/application.yml
  domain/src/main/java/com/letter/question/service/AnswerService.java
  domain/src/main/java/com/letter/question/service/QuestionService.java
  storage/src/main/java/com/letter/member/entity/Couple.java
  storage/src/main/java/com/letter/question/entity/Answer.java
  storage/src/main/java/com/letter/question/repository/AnswerCustomRepositoryImpl.java
  storage/src/main/java/com/letter/question/repository/SelectQuestionRepository.java
Labels: fix

#83 chore: 멀티 모듈 설정 수정
  .github/workflows/deploy.yml
  build.gradle
  common/build.gradle
  domain/build.gradle
  storage/build.gradle
Labels: refactor, chore

#84 chore: deploy.yml, Dockerfile 수정
  .github/workflows/deploy.yml
  common/Dockerfile
Labels: chore

#85 style: 에러 확인용 주석 처리
  common/src/main/resources/application-prod.yml
Labels: style

#86 feat: parameter store 관련 설정 추가
  common/build.gradle
  common/src/main/resources/application-prod.yml
Labels: feature

#82 feat: 답변 등록 렌더링 관련 데이터 조회 #81
  common/src/main/java/com/letter/question/AnswerController.java
  domain/src/main/java/com/letter/question/service/AnswerService.java
  storage/src/main/java/com/letter/question/dto/QuestionContentsResponse.java
  storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
Labels: feature

#87 chore: parameter store 관련 설정 변경
  common/build.gradle
  common/src/main/resources/application-prod.yml
Labels: chore

#88 chore: 포트 변호 변경
  common/src/main/resources/application-prod.yml
Labels: chore

#89 Dev
  common/src/main/java/com/letter/annotation/LoginCheck.java
  common/src/main/java/com/letter/interceptor/LoginCheckInterceptor.java
  common/src/main/java/com/letter/member/MemberController.java
  common/src/main/java/com/letter/question/AnswerController.java
  common/src/main/resources/application.yml
  domain/src/main/java/com/letter/member/MemberService.java
  domain/src/main/java/com/letter/question/service/AnswerService.java
  domain/src/main/java/com/letter/question/service/QuestionService.java
  storage/src/main/java/com/letter/exception/ErrorCode.java
  storage/src/main/java/com/letter/member/dto/MemberResponse.java
  storage/src/main/java/com/letter/member/entity/Couple.java
  storage/src/main/java/com/letter/member/entity/InviteOpponent.java
  storage/src/main/java/com/letter/member/repository/InviteOpponentCustomRepository.java
  storage/src/main/java/com/letter/member/repository/InviteOpponentCustomRepositoryImpl.java
  storage/src/main/java/com/letter/question/dto/QuestionContentsResponse.java
  storage/src/main/java/com/letter/question/entity/Answer.java
  storage/src/main/java/com/letter/question/repository/AnswerCustomRepositoryImpl.java
  storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
  storage/src/main/java/com/letter/question/repository/SelectQuestionRepository.java
Labels: feature, fix, refactor, chore

#97 fix: 로그인 redirect_uri 가 서로 다른 경우 발생하는 에러 해결 #96
  domain/src/main/java/com/letter/member/OAuthService.java
Labels: fix

#100 feat: 초대 링크 생성 api 에 response 추가 #99
  domain/src/main/java/com/letter/member/MemberService.java
  storage/src/main/java/com/letter/member/dto/MemberRequest.java
  storage/src/main/java/com/letter/member/dto/MemberResponse.java
Labels: feature

#102 refactor: yml 수정
  domain/src/main/resources/application-domain.yml
  storage/src/main/resources/application-sotrage.yml
Labels: refactor

#103 refactor: jwt secret 오타 수정
  domain/src/main/java/com/letter/jwt/JwtProperties.java
Labels: refactor

#104 refactor: JwtProperties 관련 수정
  common/src/main/java/com/letter/aws/EbHealthCheck.java
  common/src/main/java/com/letter/interceptor/LoginCheckInterceptor.java
  common/src/main/java/com/letter/interceptor/LoginUserArgumentResolver.java
  common/src/main/resources/application.yml
  domain/src/main/java/com/letter/jwt/JwtProperties.java
  domain/src/main/java/com/letter/jwt/JwtProvider.java
  domain/src/main/resources/application-domain.yml
Labels: refactor

#105 refactor: 테스트용 API 삭제
  common/src/main/java/com/letter/aws/EbHealthCheck.java
Labels: refactor

#108 feat: 질문, 답변 API에 인증, 유저 정보 받기 어노테이션 추가 #106
  common/src/main/java/com/letter/question/AnswerController.java
  common/src/main/java/com/letter/question/QuestionController.java
  common/src/main/resources/application.yml
  domain/src/main/java/com/letter/question/service/AnswerService.java
  domain/src/main/java/com/letter/question/service/QuestionService.java
Labels: feature

#109 Dev
  common/src/main/java/com/letter/question/AnswerController.java
  common/src/main/java/com/letter/question/QuestionController.java
  common/src/main/resources/application.yml
  domain/src/main/java/com/letter/question/service/AnswerService.java
  domain/src/main/java/com/letter/question/service/QuestionService.java
Labels: feature

#111 refactor: jwtProperties 파일 삭제 및 로그인 관련 key yml 파일로 빼기 #110
  common/src/main/resources/application-local.yml
  common/src/main/resources/application-prod.yml
  common/src/main/resources/application.yml
  domain/src/main/java/com/letter/jwt/JwtProperties.java
  domain/src/main/java/com/letter/jwt/JwtProvider.java
  domain/src/main/java/com/letter/member/OAuthService.java
Labels: refactor

#113 refactor: 질문 조회 로직 수정 #112
  domain/src/main/java/com/letter/question/service/AnswerService.java
  domain/src/main/java/com/letter/question/service/QuestionService.java
  storage/src/main/java/com/letter/member/repository/CoupleCustomRepositoryImpl.java
  storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
Labels: refactor

#116 fix: 초대 링크 생성 api에 커플 관련 유효성 추가 및 초대 수락 api 답변 등록 로직 수정 #115
  domain/src/main/java/com/letter/member/MemberService.java
  storage/src/main/java/com/letter/exception/ErrorCode.java
  storage/src/main/java/com/letter/member/dto/MemberRequest.java
  storage/src/main/java/com/letter/question/entity/Answer.java
Labels: fix

#118 Dev
  domain/src/main/java/com/letter/member/MemberService.java
  storage/src/main/java/com/letter/exception/ErrorCode.java
  storage/src/main/java/com/letter/member/dto/MemberRequest.java
  storage/src/main/java/com/letter/question/entity/Answer.java
Labels: deploy
