Repository coding-union-kr/youare-iam-be, pull requests merged in 2024-02, with the labels that each got.

#151 feat, refactor: Member 도메인 Swagger 설정 추가 및 변경 #30
  common/src/main/java/com/letter/config/SwaggerConfig.java
  common/src/main/java/com/letter/interceptor/LoginUserArgumentResolver.java
  common/src/main/java/com/letter/member/MemberController.java
  domain/src/main/java/com/letter/exception/ErrorCode.java
  domain/src/main/java/com/letter/member/MemberService.java
  storage/src/main/java/com/letter/member/dto/MemberRequest.java
  storage/src/main/java/com/letter/member/dto/MemberResponse.java
  storage/src/main/java/com/letter/member/dto/MemberStatusResponse.java
  storage/src/main/java/com/letter/member/entity/Member.java
  storage/src/main/java/com/letter/security/CryptoHelper.java
Labels: feature, refactor

#152 feat: 사용자 답변 암호화 #52
  storage/src/main/java/com/letter/member/entity/InviteOpponent.java
  storage/src/main/java/com/letter/question/entity/Answer.java
Labels: feature

#154 comment: 불필요한 정보성 로그 삭제 #153
  common/src/main/java/com/letter/interceptor/LoginUserArgumentResolver.java
  storage/src/main/java/com/letter/security/CryptoHelper.java
Labels: comment

#155 Deploy
  common/src/main/java/com/letter/config/SwaggerConfig.java
  common/src/main/java/com/letter/interceptor/LoginCheckInterceptor.java
  common/src/main/java/com/letter/interceptor/LoginUserArgumentResolver.java
  common/src/main/java/com/letter/member/MemberController.java
  common/src/main/java/com/letter/member/OAuthController.java
  common/src/main/java/com/letter/question/QuestionController.java
  domain/src/main/java/com/letter/exception/ErrorCode.java
  domain/src/main/java/com/letter/jwt/JwtProvider.java
  domain/src/main/java/com/letter/member/MemberService.java
  domain/src/main/java/com/letter/member/OAuthService.java
  storage/src/main/java/com/letter/member/dto/MemberRequest.java
  storage/src/main/java/com/letter/member/dto/MemberResponse.java
  storage/src/main/java/com/letter/member/dto/MemberStatusResponse.java
  storage/src/main/java/com/letter/member/dto/role/UserStatusRole.java
  storage/src/main/java/com/letter/member/entity/InviteOpponent.java
  storage/src/main/java/com/letter/member/entity/Member.java
  storage/src/main/java/com/letter/member/repository/InviteOpponentCustomRepositoryImpl.java
  storage/src/main/java/com/letter/question/entity/Answer.java
  storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
  storage/src/main/java/com/letter/security/CryptoHelper.java
Labels: deploy

#156 feat: 하루에 질문 한개 등록 제한 기능 추가 #53
  domain/src/main/java/com/letter/exception/ErrorCode.java
  domain/src/main/java/com/letter/question/service/QuestionService.java
  storage/src/main/java/com/letter/question/repository/SelectQuestionCustomRepository.java
  storage/src/main/java/com/letter/question/repository/SelectQuestionCustomRepositoryImpl.java
Labels: feature

#157 Deploy
  domain/src/main/java/com/letter/exception/ErrorCode.java
  domain/src/main/java/com/letter/question/service/QuestionService.java
  storage/src/main/java/com/letter/question/repository/SelectQuestionCustomRepository.java
  storage/src/main/java/com/letter/question/repository/SelectQuestionCustomRepositoryImpl.java
Labels: deploy

#159 Deploy
  common/src/main/resources/application.yml
Labels: deploy

#161 Deploy
  common/Dockerfile
  common/src/main/java/com/letter/interceptor/LoginCheckInterceptor.java
Labels: deploy

#162 !HOTFIX: CORS 허용 오리진 제한으로 보안 강화
  common/src/main/java/com/letter/config/WebConfig.java
  common/src/main/resources/application.yml
  domain/src/main/resources/application-domain-dev.yml
  domain/src/main/resources/application-domain-local.yml
  domain/src/main/resources/application-domain-prod.yml
  domain/src/main/resources/application-domain.yml
  storage/src/main/resources/application-sotrage.yml
  storage/src/main/resources/application-storage-dev.yml
  storage/src/main/resources/application-storage-local.yml
  storage/src/main/resources/application-stroage-prod.yml
Labels: !HOTFIX

#163 Deploy
  common/src/main/java/com/letter/config/WebConfig.java
  common/src/main/resources/application.yml
  domain/src/main/resources/application-domain-dev.yml
  domain/src/main/resources/application-domain-local.yml
  domain/src/main/resources/application-domain-prod.yml
  domain/src/main/resources/application-domain.yml
  storage/src/main/resources/application-sotrage.yml
  storage/src/main/resources/application-storage-dev.yml
  storage/src/main/resources/application-storage-local.yml
  storage/src/main/resources/application-stroage-prod.yml
Labels: deploy

#164 deploy: CORS 허용 오리진 변경
  common/src/main/java/com/letter/config/WebConfig.java
  common/src/main/resources/application.yml
Labels: deploy

#165 Deploy
  common/src/main/java/com/letter/config/WebConfig.java
  common/src/main/resources/application.yml
Labels: deploy

#169 feat: 컨테이너 내의 서버 시간 설정 추가
  common/src/main/java/com/letter/CommonApplication.java
Labels: feature

#170 Deploy
  common/src/main/java/com/letter/CommonApplication.java
Labels: deploy

#171 !HOTFIX: 컨테이너 내의 서버 시간 설정 변경
  common/Dockerfile
  common/src/main/java/com/letter/CommonApplication.java
Labels: !HOTFIX

#172 Deploy
  common/Dockerfile
  common/src/main/java/com/letter/CommonApplication.java
Labels: deploy

#174 feat: 답변 수정 #173
  common/src/main/java/com/letter/question/AnswerController.java
  domain/src/main/java/com/letter/question/service/AnswerService.java
  storage/src/main/java/com/letter/question/dto/ModifyAnswerRequest.java
  storage/src/main/java/com/letter/question/entity/Answer.java
  storage/src/main/java/com/letter/question/repository/AnswerRepository.java
  storage/src/main/java/com/letter/question/repository/SelectQuestionCustomRepositoryImpl.java
Labels: feature

#176 feat: 기존 답변 조회 #175
  common/src/main/java/com/letter/question/AnswerController.java
  domain/src/main/java/com/letter/exception/ErrorCode.java
  domain/src/main/java/com/letter/question/service/AnswerService.java
  storage/src/main/java/com/letter/question/dto/AnswerContentsResponse.java
  storage/src/main/java/com/letter/question/repository/AnswerCustomRepositoryImpl.java
  storage/src/main/java/com/letter/question/repository/SelectQuestionCustomRepositoryImpl.java
Labels: feature, !BREAKING CHANGE

#179 Deploy
  common/src/main/java/com/letter/question/AnswerController.java
  domain/src/main/java/com/letter/exception/ErrorCode.java
  domain/src/main/java/com/letter/question/service/AnswerService.java
  storage/src/main/java/com/letter/question/dto/AnswerContentsResponse.java
  storage/src/main/java/com/letter/question/dto/ModifyAnswerRequest.java
  storage/src/main/java/com/letter/question/entity/Answer.java
  storage/src/main/java/com/letter/question/repository/AnswerCustomRepositoryImpl.java
  storage/src/main/java/com/letter/question/repository/AnswerRepository.java
  storage/src/main/java/com/letter/question/repository/SelectQuestionCustomRepositoryImpl.java
Labels: deploy

#180 refactor: Request 유효성 체크 #178
  common/build.gradle
  common/src/main/java/com/letter/member/MemberController.java
  common/src/main/java/com/letter/question/AnswerController.java
  common/src/main/java/com/letter/question/QuestionController.java
  domain/build.gradle
  domain/src/main/java/com/letter/exception/ExceptionResponse.java
  domain/src/main/java/com/letter/exception/handler/GlobalExceptionHandler.java
  domain/src/main/java/com/letter/question/service/AnswerService.java
  domain/src/main/java/com/letter/question/service/QuestionService.java
  storage/src/main/java/com/letter/member/dto/MemberRequest.java
  storage/src/main/java/com/letter/question/dto/AnswerRequest.java
  storage/src/main/java/com/letter/question/dto/ModifyAnswerRequest.java
  storage/src/main/java/com/letter/question/dto/QuestionRequest.java
Labels: refactor
