Repository coding-union-kr/youare-iam-be, pull requests merged in 2024-01, with the labels that each got.

#120 feat: 사용자 정보 암복호화 #119
  common/src/main/resources/application-local.yml
  storage/src/main/java/com/letter/member/entity/Member.java
  storage/src/main/java/com/letter/security/CryptoHelper.java
  storage/src/main/java/com/letter/security/CryptoStringConverter.java
Labels: feature

#123 Deploy
  common/src/main/resources/application-local.yml
  storage/src/main/java/com/letter/member/entity/Member.java
  storage/src/main/java/com/letter/security/CryptoHelper.java
  storage/src/main/java/com/letter/security/CryptoStringConverter.java
Labels: deploy

#122 refactor: 대화 상세 API 요구사항 추가 #121
  domain/src/main/java/com/letter/question/service/QuestionService.java
  storage/src/main/java/com/letter/question/dto/LetterPaginationDto.java
Labels: refactor

#125 fix: 초대 수락 api 에 유효성 체크 로직 추가 #124
  domain/src/main/java/com/letter/member/MemberService.java
  storage/src/main/java/com/letter/member/repository/InviteOpponentCustomRepositoryImpl.java
Labels: fix

#126 feat: Refresh token 발급 #12
  common/src/main/java/com/letter/member/OAuthController.java
  domain/src/main/java/com/letter/jwt/JwtProvider.java
  domain/src/main/java/com/letter/member/OAuthService.java
  storage/src/main/java/com/letter/exception/ErrorCode.java
  storage/src/main/java/com/letter/member/entity/Member.java
  storage/src/main/java/com/letter/member/repository/MemberCustomRepositoryImpl.java
Labels: feature

#128 fix: 초대 수락 api에 유효성 체크 로직 추가
  domain/src/main/java/com/letter/member/MemberService.java
  storage/src/main/java/com/letter/exception/ErrorCode.java
Labels: fix

#130 refactor: ErrorCode에서 code 중복 수정
  storage/src/main/java/com/letter/exception/ErrorCode.java
Labels: refactor

#133 chore: Beanstalk 환경 변수 세팅 #132
  common/src/main/resources/application-local.yml
  common/src/main/resources/application-prod.yml
  common/src/main/resources/application.yml
Labels: chore

#136 feat, refactor: Error 응답에 code 추가 #135
  domain/src/main/java/com/letter/exception/CustomException.java
  domain/src/main/java/com/letter/exception/ErrorCode.java
  domain/src/main/java/com/letter/exception/ExceptionResponse.java
  domain/src/main/java/com/letter/exception/handler/GlobalExceptionHandler.java
Labels: feature, refactor

#139 Deploy
  common/src/main/java/com/letter/member/OAuthController.java
  common/src/main/resources/application-local.yml
  common/src/main/resources/application-prod.yml
  common/src/main/resources/application.yml
  domain/src/main/java/com/letter/exception/CustomException.java
  domain/src/main/java/com/letter/exception/ErrorCode.java
  domain/src/main/java/com/letter/exception/ExceptionResponse.java
  domain/src/main/java/com/letter/exception/handler/GlobalExceptionHandler.java
  domain/src/main/java/com/letter/jwt/JwtProvider.java
  domain/src/main/java/com/letter/member/MemberService.java
  domain/src/main/java/com/letter/member/OAuthService.java
  domain/src/main/java/com/letter/question/service/QuestionService.java
  storage/src/main/java/com/letter/exception/ErrorCode.java
  storage/src/main/java/com/letter/member/entity/Member.java
  storage/src/main/java/com/letter/member/repository/InviteOpponentCustomRepositoryImpl.java
  storage/src/main/java/com/letter/member/repository/MemberCustomRepositoryImpl.java
  storage/src/main/java/com/letter/question/dto/LetterPaginationDto.java
Labels: deploy

#140 refactor: Refresh token 요구사항에 따라 변경 #131
  common/src/main/java/com/letter/interceptor/LoginCheckInterceptor.java
  common/src/main/java/com/letter/interceptor/LoginUserArgumentResolver.java
  domain/src/main/java/com/letter/exception/ErrorCode.java
  domain/src/main/java/com/letter/jwt/JwtProvider.java
  domain/src/main/java/com/letter/member/OAuthService.java
Labels: refactor

#141 feat: 만료된 토큰 검증 추가 #138
  domain/src/main/java/com/letter/jwt/JwtProvider.java
  domain/src/main/java/com/letter/member/OAuthService.java
Labels: feature

#142 feat: 초대 링크 생성/초대 수락 api 에 링크 유효시간 체크 로직 추가 #134
  domain/src/main/java/com/letter/exception/ErrorCode.java
  domain/src/main/java/com/letter/member/MemberService.java
  storage/src/main/java/com/letter/member/repository/InviteOpponentCustomRepositoryImpl.java
Labels: feature

#144 fix: nextCursor 1일 때 생기는 문제 해결 #143
  common/src/main/java/com/letter/question/QuestionController.java
  storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
Labels: fix

#146 feat: 로그인 유저 상태 확인을 위한 API 생성 #145
  common/src/main/java/com/letter/member/MemberController.java
  domain/src/main/java/com/letter/member/MemberService.java
  storage/src/main/java/com/letter/member/repository/InviteOpponentCustomRepositoryImpl.java
Labels: feature

#147 feat: 로그아웃 API 추가 #137
  common/src/main/java/com/letter/member/OAuthController.java
  domain/src/main/java/com/letter/jwt/JwtProvider.java
  domain/src/main/java/com/letter/member/OAuthService.java
  storage/src/main/java/com/letter/member/entity/Member.java
Labels: feature

#148 fix: 사용자 상태 검사 누락 파일 추가
  storage/src/main/java/com/letter/member/dto/MemberStatusResponse.java
  storage/src/main/java/com/letter/member/dto/role/UserStatusRole.java
Labels: fix

#150 fix: 초대 수락 api 에 초대한 사람과 초대된 사람이 같은지 체크하는 부분 수정 #149
  domain/src/main/java/com/letter/member/MemberService.java
Labels: fix
